---
# control
control:
  num_supervised: '1280'
  loss_mode: 'fix@0.95-mix'
  num_clients: '5'
  active_rate: '0.4'
  data_split_mode: 'iid'
  local_epoch: '5-5'
  gm: '0.5'
  sbn: '0'
  ft: '1'
# data
data_name: BDD100K
model_name: mb2-ssd-lite
# experiment
num_workers: 4
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False