---
# control
control:
  num_supervised: '4000'
  num_clients: '1'
  active_rate: '1'
  data_split_mode: 'iid'
  client_loss_mode: 'fix-mix'
  local_epoch: '5'
  gm: '0'
  weight: '1'
  naive: '0'
# data
data_name: STL10
model_name: wresnet37x2
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
