---
# control
control:
  num_users: '1'
  active_rate: '1'
  data_split_mode: 'none'
  supervise_rate: '0.08'
  student_data_name: 'none'
  student_model_name: 'none'
# data
data_name: CIFAR10
# MNIST
model_name: conv
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
