---
# control
control:
  num_users: '1'
  active_rate: '1'
  data_split_mode: 'iid'
  num_supervised: '4000'
  user_data_name: 'CIFAR10'
  user_model_name: 'conv'
  threshold: '0.3'
# data
data_name: CIFAR10
# MNIST
model_name: conv
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
