---
# control
control:
  num_users: '100'
  frac: '0.01'
  data_split_mode: 'iid'
  augment: 'ra'
# data
data_name: CIFAR10
# MNIST
model_name: wresnet28x10
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
